### ISSUE TITLE
features request : nav on key / keep keyjump mode

### ISSUE THREAD

**Issue by PaysanCorrezien** [DreamMaoMao/keyjump.yazi#2]
Hi, I just tested your plugin and its great :) 
I can see 2 changes to make it even better : 
- Make it so when we press the shortcut key we trigger the `open` so it either go on directory or open file.  Using a keybind param ? I didnt look at the code yet but making an option for this might be quite straighforward ? 
- On `nnn` file manager on Unix they have a `type to nav` : https://github.com/jarun/nnn/wiki/concepts#type-to-nav that make navigation realy fast. When the mode is triggered we can just type directory name to nav to match. I wanted to create a plugin for this  but your keyjump idea seems better. 
I think a key to toggle a `keyjump` mode could work similarly, but instead of directory name use the `hints` generated, it would be even better than the `nnn` solution. 
So the behavior i think about it : `toggle keyjump mode keybind`  -> then we just have to press hint `key` to keep `cd` into choosen `hint` matching dir, and it keep generating the `hints` each time we jump directory without repression `i` on open until we either `toggle keyjump mode keybind` or another `disable jumpmode` key (same key would probably be better). 
What do you think about the idea ? 
i didnt look into yazi api yet so maybe it's not that easy to create this right now .
Thanks,
Dylan

**Comment by DreamMaoMao** [comment]
That's a good idea. That was part of my plan.
I'll keep it the way it is now and offer another continuous mode option.

Selecting a directory in this mode will automatically enter, and will remain in keyjump mode until you press esc to exit or select a file that will automatically open and exit this mode.

**Comment by sxyazi** [comment]
Sounds fantastic!

I think it's much better than relative line number navigation and really looking forward to it!

**Comment by DreamMaoMao** [comment]
https://github.com/DreamMaoMao/keyjump.yazi/pull/4

done !  try the latest commit

```toml
[manager]

keymap = [

	# keep mode, when select a dir, it will auto enter and keep in keyjump mode.
	# when select a file or press <ESC> or select no match, it will leave keyjump mode.
	{ on = [ "i"], exec = "plugin keyjump --sync --args='sync-init keep'", desc = "keyjump" },

	# normal mode, when select a item, it will auto leave keyjump mode
	{ on = [ "i"], exec = "plugin keyjump --sync --args='sync-init normal'", desc = "keyjump" },
]
```
